### PR TITLE
Mesos docs update

### PR DESCRIPTION
**Pull request by AllenFang**

### CODE REVIEW

**Comment by jackyoh** [comment]
Thank you for your help.

**Comment by AllenFang** [comment]
some question on [here](https://github.com/jackyoh/mesos-contributor-practice/blob/master/submitting-a-patch.md#在寫-code-之前的準備)

Who is `shepherd`? , because you said he/she can be found in [committer](https://github.com/apache/mesos/blob/master/docs/committers.md), but I can't find it... 

<hr/>

> 指定一個適合的 shepherd 在 patch 裡。 

Also, I feel above sentence is little wired. lol

**Comment by jackyoh** [comment]
Shepherd is a committer. 

Following this [link](https://github.com/jackyoh/mesos-contributor-practice/blob/master/images/commiter.png) you will find.

**Comment by AllenFang** [comment]
oh,  I see, so I think you should update your README, because no one can find Shepherd at following indication[committer](https://github.com/apache/mesos/blob/master/docs/committers.md)

> shepherd 可以在 [committer](https://github.com/apache/mesos/blob/master/docs/committers.md) 的文件找到

Second, Shepherd is a person, so his name should be Shepherd instead of shepherd.

**Comment by jackyoh** [comment]
Thank you for your suggestion. I already updated the submitting-a-patch.md file.

**Pull request merged**
